name: Sync remote repositories into mirrors for mage-os distribution
on:
  schedule: # Run schedule every day at 9:57
    - cron: "57 9 * * *"
  workflow_dispatch:

jobs:
  sync-main-repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: 
          - magento2
          - magento2-sample-data
          - magento2-page-builder
          - magento-composer-installer
          - zf1
          - security-package
          - inventory
          - inventory-composer-installer
          - page-builder-types
          - composer-root-update-plugin
          - composer-dependency-version-audit-plugin 
          - module-configurable-sample-data-venia
          - devdocs
          - adobe-ims
          - adobe-stock-integration
          - composer
          - commerce-data-export
          - magento-semver
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: "2048 SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8 github.com (RSA)"
      - uses: actions/checkout@v1
      - name: Sync magento/${{ matrix.package }} repository
        run: bin/mirror-sync.sh magento/${{ matrix.package }} mage-os/mirror-${{ matrix.package }}
        shell: bash
